### ISSUE TITLE
Agregar shortcut /api/users/me/...

### ISSUE THREAD

**Issue by jlsoto85** [chrisgel15/tacs#20]
Requeriria diferenciacion de usuarios.

**Comment by EricQuinterX** [comment]
Estoy por quitar los id de los usuarios de la url porque con el token identifico que idUser tiene cada uno.
No se si te parece bien pero se me ocurrió que sea "api/user/..." (en singular)
ya que si quiero una lista de usuarios (solo el admin puede) sera **/api/admin/users/**
Que opinas??

**Comment by EricQuinterX** [comment]
Resuelto en el issue #18
En los recursos propios del usuario seran /api/user/....
